use std::fmt;

#[derive(Debug,PartialEq)]
pub enum ReservedWord {
    // Keyword
    Async,
    Await,
    Break,
    Case,
    Catch,
    Class,
    Const,
    Continue,
    Debugger,
    Default,
    Delete,
    Do,
    Else,
    Export,
    Extends,
    Finally,
    For,
    Function,
    If,
    Import,
    In,
    InstanceOf,
    Let,
    New,
    Return,
    Super,
    Switch,
    This,
    Throw,
    Try,
    TypeOf,
    Var,
    Void,
    While,
    With,
    Yield,

    // FutureReservedWord
    Enum,
    Implements,
    Interface,
    Package,
    Private,
    Protected,
    Public,

    // NullLiteral
    Null,
    // BooleanLiteral
    True,
    False,
}

impl fmt::Display for ReservedWord {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ReservedWord::Async => write!(f, "async"),
            ReservedWord::Await => write!(f, "await"),
            ReservedWord::Break => write!(f, "break"),
            ReservedWord::Case => write!(f, "case"),
            ReservedWord::Catch => write!(f, "catch"),
            ReservedWord::Class => write!(f, "class"),
            ReservedWord::Const => write!(f, "const"),
            ReservedWord::Continue => write!(f, "continue"),
            ReservedWord::Debugger => write!(f, "debugger"),
            ReservedWord::Default => write!(f, "default"),
            ReservedWord::Delete => write!(f, "delete"),
            ReservedWord::Do => write!(f, "do"),
            ReservedWord::Else => write!(f, "else"),
            ReservedWord::Export => write!(f, "export"),
            ReservedWord::Extends => write!(f, "extends"),
            ReservedWord::Finally => write!(f, "finally"),
            ReservedWord::For => write!(f, "for"),
            ReservedWord::Function => write!(f, "function"),
            ReservedWord::If => write!(f, "if"),
            ReservedWord::Import => write!(f, "import"),
            ReservedWord::In => write!(f, "in"),
            ReservedWord::InstanceOf => write!(f, "instanceof"),
            ReservedWord::Let => write!(f, "let"),
            ReservedWord::New => write!(f, "new"),
            ReservedWord::Return => write!(f, "return"),
            ReservedWord::Super => write!(f, "super"),
            ReservedWord::Switch => write!(f, "switch"),
            ReservedWord::This => write!(f, "this"),
            ReservedWord::Throw => write!(f, "throw"),
            ReservedWord::Try => write!(f, "try"),
            ReservedWord::TypeOf => write!(f, "typeof"),
            ReservedWord::Var => write!(f, "var"),
            ReservedWord::Void => write!(f, "void"),
            ReservedWord::While => write!(f, "while"),
            ReservedWord::With => write!(f, "with"),
            ReservedWord::Yield => write!(f, "yield"),
            ReservedWord::Enum => write!(f, "enum"),
            ReservedWord::Implements => write!(f, "implements"),
            ReservedWord::Interface => write!(f, "interface"),
            ReservedWord::Package => write!(f, "package"),
            ReservedWord::Private => write!(f, "private"),
            ReservedWord::Protected => write!(f, "protected"),
            ReservedWord::Public => write!(f, "public"),
            ReservedWord::Null => write!(f, "null"),
            ReservedWord::True => write!(f, "true"),
            ReservedWord::False => write!(f, "false"),
        }
    }
}
