version: 2
jobs:
  test:
    docker:
      - image: rust:1.39
    steps:
      - checkout
      - restore_cache:
          keys:
            - packages-v1-{{ .Branch }}
      - run:
          command: cargo fetch
      - save_cache:
          key: packages-v1-{{ .Branch }}
          paths:
            - "~/.cargo"
      - run:
          command: cargo test
workflows:
  version: 2
  test:
    jobs:
      - test
